 CREATE SCHEMA PIZZABOX;
USE PIZZABOX;
CREATE TABLE USER
(
	Username	CHAR(30)	NOT NULL UNIQUE,
    Pass		CHAR(30)	NOT NULL,
    FullName	CHAR(60)	NOT NULL,	
    SessionLive	TINYINT		NOT NULL, -- Session state
    CONSTRAINT	USER_PK		PRIMARY KEY(Username)
);
CREATE TABLE STORE
(
	StoreID		MEDIUMINT		NOT NULL UNIQUE AUTO_INCREMENT,
    City		CHAR(255)		NOT NULL,
    State		CHAR(2)			NOT NULL,
    Zip			CHAR(10)		NOT NULL,
    CONSTRAINT 	Location 		UNIQUE (City, State),
    CONSTRAINT	STORE_PK		PRIMARY KEY(StoreID)
);
CREATE TABLE INVENTORY
(
	StoreID		MEDIUMINT		NOT NULL UNIQUE,
    Preset		MEDIUMINT		NOT NULL,
    Custom		MEDIUMINT		NOT NULL,
    CONSTRAINT	INV_PK			PRIMARY KEY(StoreID),
    CONSTRAINT	INV_STORE_FK	FOREIGN KEY(StoreID)
	REFERENCES	STORE(StoreID)
    ON UPDATE NO ACTION
    ON DELETE CASCADE
);
CREATE TABLE ORD
(
    OrderID		BIGINT			NOT NULL UNIQUE AUTO_INCREMENT,
    StoreID		MEDIUMINT		NOT NULL,
    User		CHAR(30)		NOT NULL,
    Pizzas		MEDIUMINT		NOT NULL,
    OD			VARCHAR(255)		NOT NULL,
    OT			VARCHAR(255)		NOT NULL,
    Preset		CHAR(36)		NOT NULL,
    Custom		CHAR(36)		NOT NULL,
    Cost		DOUBLE			NOT NULL,
    CONSTRAINT	ORDERS_PK		PRIMARY KEY(OrderID),
    CONSTRAINT	ORDERS_STORE_FK	FOREIGN KEY(StoreID)
    REFERENCES	STORE(StoreID)
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
    CONSTRAINT ORDERS_USER_FK	FOREIGN KEY(User)
    REFERENCES `USER`(Username)
    ON UPDATE CASCADE
    ON DELETE NO ACTION
);

INSERT INTO STORE(City,State,Zip)VALUES('Arlington','TX','76001');
INSERT INTO INVENTORY(StoreID,Preset,Custom)VALUES(1, 1000, 1000);


